#!/usr/bin/env sh

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

source "$ITEM_DIR/spaces.sh"
source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

# Setting up the general bar appearance of the bar
bar=(
  height=32
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=5
  padding_left=5
  corner_radius=9
  y_offset=10
  margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=0
  background.height=20
  background.corner_radius=5
  background.color=$BACKGROUND_1
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item app-icon left \
           --set app-icon icon.drawing=off background.color=$ICON_BACKGROUND script="$PLUGIN_DIR/app-icon.sh" \
           --subscribe app-icon front_app_switched \
           --add item frontApp.separator left \
           --set frontApp.separator \
                background.padding_left=-3 \
                icon= \
                icon.font="FiraCode Nerd Font:Bold:16.0" \
                icon.color=$ICON_BACKGROUND \
                icon.padding_left=0 \
                icon.padding_right=0 \
                label.drawing=no \
           --add item front_app left \
           --set front_app icon.drawing=off padding_left=0 script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched
sketchybar --add bracket frontAppBracket \
            app-icon \
            front_app \
            --subscribe front_app front_app_switched \
##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 padding_left=5 icon.drawing=off script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume padding_left=5 script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
