#!/usr/bin/env sh

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored
LLM_UPDATE_FREQ=900
LLM_CACHE_TTL=900
export LLM_CACHE_TTL

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$ITEM_DIR/spaces.sh"
##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

# Setting up the general bar appearance of the bar
bar=(
  height=32
  color=$BAR_COLOR
  shadow=off
  position=top
  sticky=on
  padding_right=5
  padding_left=5
  corner_radius=9
  y_offset=10
  margin=10
  blur_radius=20
  notch_width=0
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=0
  background.height=20
  background.corner_radius=5
  background.color=$BACKGROUND_1
  icon.font="Hack Nerd Font:Regular:17.0"
  label.font="Hack Nerd Font:Regular:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item app-icon left \
           --set app-icon script="$PLUGIN_DIR/app-icon.sh" \
           --subscribe app-icon front_app_switched \
           --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \

sketchybar --add bracket frontAppBracket \
            app-icon \
            front_app \
            --subscribe front_app front_app_switched \

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 padding_left=5 icon.drawing=off script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume padding_left=5 script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change

sketchybar --add item llm_copilot right \
           --set llm_copilot update_freq=$LLM_UPDATE_FREQ \
                            icon="" \
                            icon.font="Hack Nerd Font:Regular:14.0" \
                            icon.color=$BLACK \
                            icon.padding_left=7 \
                            icon.padding_right=4 \
                            icon.background.drawing=on \
                            icon.background.color=$BLUE \
                            icon.background.height=20 \
                            icon.background.corner_radius=5 \
                            label="--" \
                            label.drawing=on \
                            label.padding_left=6 \
                            label.padding_right=8 \
                            background.drawing=on \
                            background.color=$BACKGROUND_1 \
                            background.height=20 \
                            background.corner_radius=5 \
                            padding_right=5 \
                            click_script="$PLUGIN_DIR/llm_usage.sh --toggle" \
                            script="$PLUGIN_DIR/llm_usage.sh" \
                            popup.background.color=$BACKGROUND_1 \
                            popup.background.corner_radius=5 \
                            popup.background.drawing=on \
           --add item llm_gemini popup.llm_copilot \
           --set llm_gemini icon="" \
                           icon.font="Hack Nerd Font:Regular:13.0" \
                           icon.color=$BLACK \
                           icon.padding_left=6 \
                           icon.padding_right=4 \
                           icon.background.drawing=on \
                           icon.background.color=$BLUE \
                           icon.background.height=20 \
                           icon.background.corner_radius=5 \
                           label="--" \
                           label.drawing=on \
                           label.padding_left=6 \
                           label.padding_right=8 \
                           background.drawing=on \
                           background.color=$BACKGROUND_1 \
                           background.height=20 \
                           background.corner_radius=5 \
           --add item llm_cursor popup.llm_copilot \
           --set llm_cursor icon="" \
                           icon.font="Hack Nerd Font:Regular:13.0" \
                           icon.color=$BLACK \
                           icon.padding_left=6 \
                           icon.padding_right=4 \
                           icon.background.drawing=on \
                           icon.background.color=$BLUE \
                           icon.background.height=20 \
                           icon.background.corner_radius=5 \
                           label="--" \
                           label.drawing=on \
                           label.padding_left=6 \
                           label.padding_right=8 \
                           background.drawing=on \
                           background.color=$BACKGROUND_1 \
                           background.height=20 \
                           background.corner_radius=5

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
